-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 15:49:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hivemind
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HiveMind
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HiveMind` DEFAULT CHARACTER SET utf8 ;
USE `HiveMind` ;

-- -----------------------------------------------------
-- Table `HiveMind`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HiveMind`.`users` ;

CREATE TABLE IF NOT EXISTS `HiveMind`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(90) NOT NULL,
  `user_lastName` VARCHAR(90) NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(150) NOT NULL,
  `user_dateOfBirth` VARCHAR(45) NULL,
  `user_phoneNumber` VARCHAR(45) NULL,
  `user_isActivated` ENUM('Active', 'Inactive') NULL DEFAULT 'Active',
  `user_lastLogin` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HiveMind`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HiveMind`.`groups` ;

CREATE TABLE IF NOT EXISTS `HiveMind`.`groups` (
  `group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(90) NOT NULL,
  `group_description` VARCHAR(360) NOT NULL,
  `group_image` VARCHAR(90) NULL,
  `group_createdAt` DATE NOT NULL,
  `group_status` ENUM("Active", "Inactive", "Archived") NULL DEFAULT 'Active',
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC) VISIBLE,
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HiveMind`.`users_in_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HiveMind`.`users_in_group` ;

CREATE TABLE IF NOT EXISTS `HiveMind`.`users_in_group` (
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `joinedAt` DATE NOT NULL,
  `role_in_group` ENUM("owner", "admin", "leader", "user") NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `group_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `HiveMind`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `HiveMind`.`groups` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
